import "./globals.css";
import "./flaticon.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Footer, Header } from "@/components";

config.autoAddCss = false;
const rubik = Rubik({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} scroll-smooth`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
